matrix:
  include:

    # OSX GCC ---------------

    - os: osx
      dist: trusty
      sudo: required
      language: cpp
      compiler: gcc

      script:
        - cmake .
        - cmake --build .
        - make
        - cd test
        - ./algo_tests

    # OSX CLANG -------------

    - os: osx
      dist: trusty
      sudo: required
      language: cpp
      compiler: clang

      script:
        - cmake .
        - cmake --build .
        - make
        - cd test
        - ./algo_tests

    # Linux GCC -------------

    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      compiler: gcc

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake

      before_install:
        - cwd=$(pwd)
        - sudo apt purge --auto-remove cmake
        - version=3.17
        - build=3
        - mkdir ~/temp
        - cd ~/temp
        - wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
        - tar -xzvf cmake-$version.$build.tar.gz
        - cd cmake-$version.$build/
        - ./bootstrap
        - make -j$(nproc)
        - sudo make install

      script:
        - cd $cwd
        - export CC=/usr/bin/gcc-6
        - export CXX=/usr/bin/g++-6
        # Build
        - cmake .
        - cmake --build .
        - make
        - cd test
        - ./algo_tests