dist: trusty
sudo: required
language: cpp
os: osx

script:
  - cmake .
  - cmake --build .

after_script:
  - cd test
  - ./algo_tests

after_success:
  - echo "SUCCESS"

after_failure:
  - echos "FAILURE"