matrix:
  include:

    # OSX GCC ---------------

    - os: osx
      dist: trusty
      sudo: required
      language: cpp
      compiler: gcc

      script:
        - cmake .
        - cmake --build .
        - make
        - cd test
        - ./algo_tests

    # OSX CLANG -------------

    - os: osx
      dist: trusty
      sudo: required
      language: cpp
      compiler: clang

      script:
        - cmake .
        - cmake --build .
        - make
        - cd test
        - ./algo_tests

    # Linux GCC -------------

    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      compiler: gcc

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake

      before_install:
        - sudo apt get install cmake

      script:
        - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
        - ln -s /usr/bin/g++-6 /usr/local/bin/g++
        - export CC=/usr/bin/gcc-6
        - export CXX=/usr/bin/g++-6
        - gcc -v && g++ -v && cmake --version
        # Run your build
        - mkdir build
        - cd build
        - cmake ..
        - make
        - cd test
        - ./algo_test