dist: trusty
sudo: required
language: cpp
os: osx

before_install:
  - pip install cpp-coveralls

script:
  - ./configure --enable-gcov && make && make check
  - cmake .
  - cmake --build .
  - make
  - cd test
  - ./algo_tests

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'