dist: trusty
sudo: required
language: cpp

matrix:
  include:

    - os: osx

      compiler:
        - gcc

      script:
        - cmake .
        - cmake --build .
        - make
        - cd test
        - ./algo_tests


    - os: linux

      compiler:
        - clang
        - gcc

      script:
        - mkdir build
        - cd build
        - cmake .. && make


