# //////////////////////////////////////////////////////////
# author: alex011235
# https://github.com/alex011235/algorithm
# //////////////////////////////////////////////////////////
# \todo{alex011235} Add Windows as target OS.

matrix:
  include:

    # OSX GCC ---------------

    - os: osx
      sudo: required
      language: cpp
      compiler: gcc

      script:
        - cmake .
        - cmake --build . -- -j2
        - make
        - cd test
        - ctest -j2

    # OSX CLANG -------------

    - os: osx
      sudo: required
      language: cpp
      compiler: clang

      script:
        - cmake .
        - cmake --build . -- -j2
        - make
        - cd test
        - ctest -j2

    # Linux GCC -------------

    - os: linux
      dist: bionic
      sudo: required
      language: cpp
      compiler: gcc

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake

      script:
        - cmake . -DENABLE_COVERAGE=1
        - cmake --build . -- -j2
        - ctest -j2
        - bash <(curl -s https://codecov.io/bash)