dist: trusty
sudo: required
language: cpp
compiler:
  - gcc

matrix:
  include:

    - os: osx

      script:
        - cmake .
        - cmake --build .
        - make
        - cd test
        - ./algo_tests
