dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
os: osx

before_install:
  - eval "$(pyenv init -)"
  - pyenv install 2.7.6
  - pyenv global 2.7.6
  - pyenv rehash
  - pip install cpp-coveralls
  - pyenv rehash

script:
  - ./configure --enable-gcov
  - cmake .
  - cmake --build .
  - make
  - cd test
  - ./algo_tests

after_success:
  - coveralls