dist: trusty
sudo: required
language: cpp
os: osx

before_install:
  - pip install --user cpp-coveralls

script:
  - cmake .
  - cmake --build .
  - make
  - cd test
  - ./algo_tests

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'