dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6


script:
  - cmake --build .
  - cd cmake-build-debug
  - ./Algorithm_test_run
