language: cpp
sudo: false
dist: trusty

git:
  submodules: true

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0

script:
  - CXX=/usr/bin/clang++-5.0 CC=/usr/bin/clang-5.0 cmake .
  - cmake --build .