# //////////////////////////////////////////////////////////
# author: alex011235
# https://github.com/alex011235/algorithm
# //////////////////////////////////////////////////////////
# \todo{alex011235} Add Windows as target OS.

matrix:
  include:

    # OSX GCC ---------------

    - os: osx
      sudo: required
      language: cpp
      compiler: gcc

      script:
        - cmake .
        - cmake --build .
        - make
        - cd test
        - ./algo_tests

    # OSX CLANG -------------

    - os: osx
      sudo: required
      language: cpp
      compiler: clang

      script:
        - cmake .
        - cmake --build .
        - make
        - cd test
        - ./algo_tests

    # Linux GCC -------------

    - os: linux
      dist: bionic
      sudo: required
      language: cpp
      compiler: gcc

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake

      before_install:
        - pip install --user cpp-coveralls

      script:
        - ./configure --enable-gcov
        - export CC=/usr/bin/gcc-6
        - export CXX=/usr/bin/g++-6
        # Build
        - cmake .
        - cmake --build .
        - make
        - cd test
        - ./algo_tests

      after_success:
        - coveralls --exclude lib --exclude tests --gcov-options '\-lp'